services:
  - type: web
    name: alris-uidai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: UIDAI_API_KEY
        sync: false
      - key: ANVIL_UPLINK_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
